CREATE TABLE IF NOT EXISTS ITEMS (
    ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS key_value (
  key TEXT NOT NULL PRIMARY KEY,
  ID INTEGER,
  value,
  UNIQUE(ID)
  UNIQUE(key)
);

CREATE TABLE IF NOT EXISTS server_id (
  server TEXT NOT NULL PRIMARY KEY,
  ID INTEGER,
  UNIQUE(ID)
  UNIQUE(server)
);
